// <auto-generated />
using System;
using EFGetStarted;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessEF.Migrations
{
    [DbContext(typeof(CountingCaloriesContext))]
    [Migration("20200712085653_dbchanges")]
    partial class dbchanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("CountingCalories.UI.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaloriesPer100g")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("CountingCalories.UI.Models.FoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodInDayId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FoodPerDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoodPerDayId");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("CountingCalories.UI.Models.FoodPerDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoodInDays");
                });

            modelBuilder.Entity("CountingCalories.UI.Models.FoodEntry", b =>
                {
                    b.HasOne("CountingCalories.UI.Models.FoodPerDay", null)
                        .WithMany("AllFoodEntries")
                        .HasForeignKey("FoodPerDayId");
                });
#pragma warning restore 612, 618
        }
    }
}
