// <auto-generated />
using System;
using CountingCalories.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CountingCalories.DataAccess.Migrations
{
    [DbContext(typeof(CountingCaloriesContext))]
    [Migration("20201006191750_NextMigration")]
    partial class NextMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("CountingCalories.Domain.Entities.FoodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaloriesPer100G")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("CountingCalories.Domain.Entities.FoodEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodPerDayDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FoodPerDayEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoodPerDayEntityId");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("CountingCalories.Domain.Entities.FoodPerDayEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Day")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoodPerDays");
                });

            modelBuilder.Entity("CountingCalories.Domain.Entities.FoodEntryEntity", b =>
                {
                    b.HasOne("CountingCalories.Domain.Entities.FoodPerDayEntity", null)
                        .WithMany("AllEntries")
                        .HasForeignKey("FoodPerDayEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
